Sync main branch with release
sotopia-lab/sotopia pull request #106
Opened 2024-06-14 20:13 UTC by ProKil

2024-06-15 19:36 UTC, ProKil commented
@XuhuiZhou Please review this PR

2024-06-16 22:18 UTC, XuhuiZhou requested changes

2024-06-16 22:18 UTC, XuhuiZhou commented on README.md
>  * [05/2024] We release [a simple tutorial](https://colab.research.google.com/drive/14hJOfzpA37PRUzdlFgiqVzUGIhhngqnz?usp=sharing) for you to run sotopia end-to-end on google colab.
Link this to the tutorial section?

2024-06-17 00:44 UTC, ProKil commented
Addressed!

2024-06-17 18:13 UTC, XuhuiZhou approved these changes

2024-06-17 18:14 UTC, merged