[Automated] Merge release into main
sotopia-lab/sotopia pull request #146
Opened 2024-07-20 01:59 UTC by ProKil

Automated Pull Request

2024-07-20 21:54 UTC, XuhuiZhou requested changes

2024-07-20 21:54 UTC, XuhuiZhou commented on pyproject.toml
> +mypy = ">=1.8.0,<1.11.0"
I thought 1.11.0 is the buggy version?

2024-07-20 21:54 UTC, XuhuiZhou commented on .github/workflows/merge-release-to-main.yml
> +jobs:
what does this do? I thought the main should be the most updated branch? Or it's more like the release branch simply changes the version name?

2024-07-21 00:04 UTC, ProKil commented on pyproject.toml
> +mypy = ">=1.8.0,<1.11.0"
so <1.11.0 is the right range.

2024-07-21 01:24 UTC, XuhuiZhou approved these changes

2024-07-21 01:24 UTC, XuhuiZhou commented on .github/workflows/merge-release-to-main.yml
> +jobs:
Cool, thanks for the explanation! I think this is worthwhile to add to the contribution doc, which I will do that.

2024-07-21 01:24 UTC, merged