Deploy the api to modal
sotopia-lab/sotopia pull request #267
Opened 2024-12-13 03:27 UTC by bugsz

This pr majorly
1. Refactor the original FastAPI
2. Add deployment to modal in `modal_api_server`

I am still working on this branch

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

## ℹ Additional Information

2024-12-13 20:46 UTC, ProKil requested changes
it looks good to me, but please make sure that the pytest is passed.

2024-12-13 20:46 UTC, ProKil commented on sotopia/ui/modal_api_server.py
> +        "pydantic>=2.5.0,<3.0.0",
Why not just install sotopia? This is not useful for maintaining dependencies.

2024-12-14 00:25 UTC, XuhuiZhou requested changes
Added the modal deployment process to the doc?

2024-12-14 07:25 UTC, bugsz commented
> it looks good to me, but please make sure that the pytest is passed.

@ProKil Current `SotopiaFastAPI` inherits FastAPI and there should not be any issue. I tested on my end and it works well.

2024-12-28 16:59 UTC, merged