Use Ruff as the formatter
sotopia-lab/sotopia pull request #41
Opened 2024-04-05 14:25 UTC by ProKil

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

## ℹ Additional Information

2024-04-07 23:16 UTC, XuhuiZhou requested changes
Looks all LLM_Name is still there?

2024-04-07 23:19 UTC, ProKil commented on examples/evaluate_existing_episode.py
> +from sotopia.generation_utils.generate import LLM_Name
Yeah, using ruff as a formatter doesn't automatically remove `LLM_Name`, which can be another chore.

2024-04-11 15:00 UTC, ProKil commented on examples/evaluate_existing_episode.py
> +from sotopia.generation_utils.generate import LLM_Name
#43

2024-04-16 20:53 UTC, XuhuiZhou approved these changes

2024-04-16 20:53 UTC, merged